name: OpenDocumentReader-iOS
on: [push]

jobs:
  test:
    name: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodule
        run: git submodule update --init --recursive

      - name: Install pods
        run: pod install
      - name: Run build.sh
        run: bash build-simulator.sh

      - name: brew
        run: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
      - name: ninja
        run: brew install ninja
      # https://stackoverflow.com/a/57758679/198996
      - name: bundler
        run: gem install bundler:1.17.3
      - name: fastlane
        run: bundle install

      - name: run tests
        run: bundle exec fastlane tests
#      - uses: actions/upload-artifact@v2
#        if: ${{ always() }}
#        with:
#          name: logs
#          path: |
#            /Users/runner/Library/Developer/Xcode/DerivedData/OpenDocumentReader-*/
