name: OpenDocumentReader-iOS
on: [push]

jobs:
  build:
    name: build
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,name=iPhone 11']
          scheme: [ODR Full]
    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodule
        run: git submodule update --init --recursive
      - name: Install pods
        run: pod install
      - name: Run build.sh
        run: bash build-simulator.sh
      - name: Build
        run: |
          xcodebuild clean build -workspace OpenDocumentReader.xcworkspace -scheme "${scheme}" -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
          destination: ${{ matrix.destination }}
          scheme: ${{ matrix.scheme }}

  test:
    name: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodule
        run: git submodule update --init --recursive

      - name: Install pods
        run: pod install
      - name: Run build.sh
        run: bash build-simulator.sh

      - name: brew
        run: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
      - name: ninja
        run: brew install ninja
      # https://stackoverflow.com/a/57758679/198996
      - name: bundler
        run: gem install bundler:1.17.3
      - name: fastlane
        run: bundle install

      - name: run tests
        run: bundle exec fastlane tests
      - name: logs
        run: cat /Users/runner/Library/Developer/Xcode/DerivedData/OpenDocumentReader-*/Logs/Test/Run-ODR Full-*.xcresult/Staging/2_Test/Diagnostics/OpenDocumentReaderTests-*/OpenDocumentReaderTests-*/Session-OpenDocumentReaderTests-*.log
