name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,name=iPhone 11']
          scheme: [OpenDocumentReader]
    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodule
        run: git submodule update --init --recursive
      - name: Install pods
        run: pod install
      - name: Run build.sh
        run: bash build.sh
      - name: Build
        run: |
          xcodebuild clean build -workspace OpenDocumentReader.xcworkspace -scheme "${scheme}" -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
          destination: ${{ matrix.destination }}
          scheme: ${{ matrix.scheme }}
